#!/bin/sh

sudo add-apt-repository ppa:certbot/certbot
sudo apt-get update
sudo apt-get install -y node npm nginx certbot pyton-certbot-nginx
sudo certbot certonly --standalone
sudo cat server { \
    server_name $fqdn; \
    root /www/data; \
    location / { \
    } \
    location /api/ { \
        proxy_pass http://localhost:1024/api/; \
    } \
    location ~* \.io { \
        proxy_set_header X-Real-IP $remote_addr; \
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; \
        proxy_set_header Host $http_host; \
        proxy_set_header X-NginX-Proxy false; \
        proxy_pass http://localhost:1024; \
        proxy_redirect off; \
        proxy_http_version 1.1; \
        proxy_set_header Upgrade $http_upgrade; \
        proxy_set_header Connection "upgrade"; \
    } \
    listen [::]:443 ssl ipv6only=on http2; # managed by Certbot \
    listen 443 ssl http2; # managed by Certbot \
    ssl_certificate /etc/letsencrypt/live/$fqdn/fullchain.pem; # managed by Certbot \
    ssl_certificate_key /etc/letsencrypt/live/$fqdn/privkey.pem; # managed by Certbot \
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot \
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot \
} \
server { \
    if ($host = $fqdn) { \
        return 301 https://$host$request_uri; \
    } # managed by Certbot \
    listen 80; \
    listen [::]:80; \
    server_name $fqdn; \
    return 404; # managed by Certbot \
} > /etc/nginx/conf.d/mc.conf
sudo certbot --nginx 
sudo nginx -t
sudo nginx -s reload

